from models import User, Post, Tag, PostTag, db
from app import app

db.drop_all()
db.create_all()

neacel = User(id=1, first_name="Neacel", last_name="Saraid", image_url="https://www.shutterstock.com/image-photo/close-headshot-portrait-picture-smiling-260nw-1733598437.jpg")
johanna = User(id=2, first_name="Johanna", last_name="Gittel", image_url="https://www.shutterstock.com/image-photo/headshot-portrait-smiling-african-american-260nw-1667439898.jpg")
vida = User(id=3, first_name="Vida", last_name="Viktoria", image_url="https://www.shutterstock.com/image-photo/profile-picture-smiling-young-african-260nw-1873784920.jpg")
medhat = User(id=4, first_name="Medhat", last_name="Renesmee", image_url="https://media.istockphoto.com/id/1388253782/photo/positive-successful-millennial-business-professional-man-head-shot-portrait.jpg?s=612x612&w=0&k=20&c=uS4knmZ88zNA_OjNaE_JCRuq9qn3ycgtHKDKdJSnGdY=")
antonia = User(id=5, first_name="Antonia", last_name="Murali", image_url="https://images.pexels.com/photos/3763188/pexels-photo-3763188.jpeg?cs=srgb&dl=pexels-andrea-piacquadio-3763188.jpg&fm=jpg")
pura = User(id=6, first_name="Pura", last_name="Reynold", image_url="https://t4.ftcdn.net/jpg/04/44/53/99/360_F_444539901_2GSnvmTX14LELJ6edPudUsarbcytOEgj.jpg")
kristo = User(id=7, first_name="Kristo", last_name="Ermengardis", image_url="https://media.istockphoto.com/id/1300512215/photo/headshot-portrait-of-smiling-ethnic-businessman-in-office.jpg?s=612x612&w=0&k=20&c=QjebAlXBgee05B3rcLDAtOaMtmdLjtZ5Yg9IJoiy-VY=")
kratos = User(id=8, first_name="Kratos", last_name="Erebos", image_url="https://www.shutterstock.com/image-photo/portrait-smiling-african-american-student-260nw-1194497215.jpg")
menachem = User(id=9, first_name="Menachem", last_name="Bertil", image_url="https://www.shutterstock.com/image-photo/head-shot-portrait-close-smiling-600nw-1714666150.jpg")
sigvard = User(id=10, first_name="Sigvard", last_name="Ronalda", image_url="https://t3.ftcdn.net/jpg/03/02/09/52/360_F_302095207_iuCeDS2jIkIptfE29Wb0ldDs248FAzoi.jpg")

disability = Tag(id=1, name="disability")
navigation = Tag(id=2, name="navigation")
accessibility = Tag(id=3, name="accessibility")
memoir = Tag(id=4, name="memoir")
employment = Tag(id=5, name="employment")
jobs = Tag(id=6, name="jobs")
accessible = Tag(id=7, name="accessible")
action = Tag(id=8, name="action")
testing = Tag(id=9, name="testing")
allies = Tag(id=10, name="allies")

db.session.add(neacel)
db.session.add(johanna)
db.session.add(vida)
db.session.add(medhat)
db.session.add(antonia)
db.session.add(pura)
db.session.add(kristo)
db.session.add(kratos)
db.session.add(menachem)
db.session.add(sigvard)
db.session.add(disability)
db.session.add(navigation)
db.session.add(accessibility)
db.session.add(memoir)
db.session.add(employment)
db.session.add(jobs)
db.session.add(accessible)
db.session.add(action)
db.session.add(testing)
db.session.add(allies)
db.session.commit()

ableism = Post(id=1, title="Calling Out Ableism Just Got Easier", content="That’s a good question.  Ableism is deeply rooted in our cultural concepts. Meaning, not just what we think about, but how we structure our thinking. And, how we even think about our thinking. Like many deeply rooted things, ableism is difficult to sum up in one succinct definition, partly because there are so many points of entry.  But we can start by observing something as simple as this riddle to exemplify just how ubiquitous, and rather innocent, ableism can be:", user_id = 5)
long = Post(id=2, title="Long Days, Late Nights", content="It’s 4 a.m. and I am staring into big, sparkling brown eyes. My muñeca lovingly looks at me while downing her bottle of formula. I look back at her, feeling blessed; however, I am physically and mentally drained. Not just because caring for a newborn is exhausting, but because I am experiencing a full-on flare. My entire body hurts – from the bottoms of my feet to the roots of my hair. I have Fibromyalgia, and a lack of sleep only makes it worse.", user_id=7)
mental_health=Post(id=3, title="My Lived Experiences Shaped My Career in Mental Health", content="Up until a few months ago, I had my mind set on one goal and one goal only, and that was to become a physician and follow in my father’s footsteps. My Indian-American upbringing influenced me to believe that this was my destiny and that becoming a doctor was the “right” choice, and therefore, I entered college as a pre-medical student with a major in biochemistry. I was only somewhat interested in the basic science courses, but I knew I had to power through and try my best to get good grades, in order to become a doctor. It wasn’t until my sophomore year, however, that I had the opportunity to expand my horizons and pursue a course in general psychology, and I remember this class very clearly because the professor inspired me to switch my major to the field. As a Jesuit institution, Georgetown University, my alma mater, upholds Jesuit values and the concept of “Cura Personalis” or “care of the whole person”, and aside from being very insightful, as well as teaching us how to apply our knowledge to real-world situations, my professor emphasized this idea of “care of the whole person” and helped me realize that there are many ways to pursue my passion of helping others.", user_id=1)
eating = Post(id=4, title="Accessiblity + Eating Disorders", content="Eating disorders are one of the most common forms of invisible disabilities affecting people in the United States and globally. The Mirasol Eating Recovery Center estimates that 10-15 percent of American deal with some type of eating disorder in their lifetime. To my knowledge, outside of the medical field there is very little written about how eating disorders fit within the rubric of “disability.” This oversight may result from the assumption that eating disorders are a personal choice, an extreme diet, or just a phase. Eating disorders are serious, complex, cognitive impairments resulting from a range of social, psychological, and physiological factors that affect all genders, races, body types, and cultures—not just the white teenager girls depicted in movies and on TV. These stereotypical images further reduce the visibility of eating disorders, how they are lived, and who lives them.", user_id=5)
disorders=Post(id=5, title="Eating Disorders Futures", content="The first doctor I told about my eating disorder just replied by saying, “We need to do a blood test to see what you’ve done to yourself.” The second doctor simply said, “That explains your BMI.” The third doctor, my then long-term therapist, told me, “I’m not trained in dealing with eating disorders.” I never got to the fourth doctor because I realized these types of replies were in contradiction to my healing. What connects these scenes of disclosure is the consistent focus on my choices, on my problem, on my body, all while ignoring my voice. By sharing this, I hope to highlight the limits of current medical approaches to treating eating disorders. The major limitation is that eating disorders are too frequently treated as individual problems that exist within ones bodymind. The aim of this essay is to start a conversation, one that imagines a new model of treatment for eating disorders based on access and the social model of disability. ", user_id=10)
corona=Post(id=6, title="Coronavirus and the Shared Emotional Experience", content="What are the factors that make group therapy successful? Why do people emerge from programs, such as Alcoholics Anonymous, feeling as if they are a changed person? When I start to think about these questions, I often refer to the concept of a shared emotional experience. If you have ever come into contact with a situation where another person’s emotions affected your own, you have been an active participant in a shared emotional experience. In fact, we are biologically hard-wired to have this experience through mirror neurons, which fire in accordance with another’s emotions and actions. A shared emotional experience can prove to be extremely powerful during a crisis—it enables solidarity and provides us with the feeling that we’re all in this together. In the time of coronavirus, the feeling that we’re all in this together is especially prominent, as people come out of the woodwork to volunteer their time and help others in unexpected ways. As I reflect on these ideas, it is evident that the current pandemic has impacted me on multiple levels, but of most importance, has shaped how I view the therapeutic process. ", user_id=8)
college=Post(id=7, title="Why Every College Student With Invisible Disabilites Needs These Six Words", content="The bags are at the door. Take one last look around at your childhood, and the life you once knew.  Family.  Memories. The sense of familiarity and safety. The cultivated support systems. It’s the day you move away from home to begin your first year of college.", user_id=3)
sped = Post(id=8, title="Reimagining Special Education for Those With Invisible Disabilities", content="I recently attended a Special Education IEP (Individualized Educational Program) meeting for a boy in first grade. Academically bright, he looks just like his peers: neat, dressed in current clothing, he runs around with the latest gadgets, and wears the cool shoes. However, he was diagnosed with Pragmatic Language Impairment and Attention Deficit Hyperactivity Disorder. He’s on the Autism Spectrum, and struggles to understand the social cues of others.", user_id=6)
demolition=Post(id=9, title="The Demolition of Ableism", content="To the Government Agency whose top down directives erase, speak over, and maintain ableism in our society: we are calling you out. This is the demolition of Ableism.To the Charity whose top down directives erase, speak over, and maintain ableism in our society: we are calling you out. This is the demolition of Ableism.", user_id=3)
holiday=Post(id=10, title="4 Holiday Texts That Get It Right About Invisible Disabilities", content="The holidays are upon us. There is loud music, people everywhere, blinking lights, scratchy sweaters, different foods, smells, hugs, kisses, and cheer — whether we are feeling it or not. For those with invisible disabilities, the sensory system can reach over-load quickly. Securing a quiet place in advance may reduce the anxiety associated with all the commotion during parties and family gatherings. Don’t hesitate to ask for what you need.", user_id=8)

db.session.add(ableism)
db.session.add(long)
db.session.add(mental_health)
db.session.add(eating)
db.session.add(disorders)
db.session.add(corona)
db.session.add(college)
db.session.add(sped)
db.session.add(demolition)
db.session.add(holiday)
db.session.commit()

one=PostTag(post_id=1, tag_id=5)
two=PostTag(post_id=1, tag_id=7)
three=PostTag(post_id=2, tag_id=3)
four=PostTag(post_id=2, tag_id=10)
five=PostTag(post_id=3, tag_id=5)
six=PostTag(post_id=3, tag_id=3)
seven=PostTag(post_id=4, tag_id=7)
eight=PostTag(post_id=4, tag_id=3)
nine=PostTag(post_id=5, tag_id=2)
ten=PostTag(post_id=5, tag_id=6)
eleven=PostTag(post_id=6, tag_id=7)
twelve=PostTag(post_id=6, tag_id=2)
thirteen=PostTag(post_id=7, tag_id=6)
fourteen=PostTag(post_id=7, tag_id=1)
fifteen=PostTag(post_id=8, tag_id=8)
sixteen=PostTag(post_id=8, tag_id=9)
seventeen=PostTag(post_id=9, tag_id=3)
eighteen=PostTag(post_id=9, tag_id=4)
nineteen=PostTag(post_id=10, tag_id=4)
twenty=PostTag(post_id=10, tag_id=3)

db.session.add(one)
db.session.add(two)
db.session.add(three)
db.session.add(four)
db.session.add(five)
db.session.add(six)
db.session.add(seven)
db.session.add(eight)
db.session.add(nine)
db.session.add(ten)
db.session.add(eleven)
db.session.add(twelve)
db.session.add(thirteen)
db.session.add(fourteen)
db.session.add(fifteen)
db.session.add(sixteen)
db.session.add(seventeen)
db.session.add(eighteen)
db.session.add(nineteen)
db.session.add(twenty)
db.session.commit()

